# Generated by Django 3.0.2 on 2020-02-10 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_computer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='computer',
        ),
        migrations.AddField(
            model_name='task',
            name='dates',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 10, 21, 33, 17, 284143, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 2, 10, 21, 34, 3, 843648, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
