# Generated by Django 3.0.2 on 2020-02-13 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200213_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dates',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
