# Generated by Django 3.0.2 on 2020-02-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dates',
        ),
    ]
